engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc.js
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
   paths:
   - index.js
   - test/*.js
   - test/helpers/*.js
