version: '{build}'

environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '8'
    - nodejs_version: '6'

branches:
  only:
    - master
    - /^greenkeeper.*$/

install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor-retry npm install

test_script:
  - npm run test

build: off

deploy: off
